### ISSUE TITLE
pre-commit-hooks 2.x

### ISSUE THREAD

**Issue by asottile** [pre-commit/pre-commit-hooks#322]
just a bit of a meta issue of the things I plan to do for `pre-commit-hooks` 2.x

for the most part this shouldn't break too many, and if it does it'll provide a meaningful way forward.

Here's the current things I plan to ship as part of this update:

- [x] #92 (PR: #321): deprecate `autopep8-wrapper` for `autopep8`
    - suggests [mirrors-autopep8](https://github.com/pre-commit/mirrors-autopep8)
    - I plan to write an [all-repos](https://github.com/asottile/all-repos) fixer which migrates this automatically
- [x] #310 (PR: #324): by default set `--no-markdown-linebreak-ext` for `trailing-whitespace`
    - for the most part this'll just remove some whitespace after people upgrade, most won't notice this anyway
- [x] Remove `hooks.yaml` (PR #323)
    - [pre-commit 0.12.0](https://github.com/pre-commit/pre-commit/releases/tag/v0.12.0) was released over a year ago which introduced `.pre-commit-hooks.yaml` (January 2017)
    - [pre-commit 0.16.0](https://github.com/pre-commit/pre-commit/releases/tag/v0.16.0) was released over a year ago which dropped support for `hooks.yaml` (August 2017)
- [x] remove the 0.15.0 compatibility metadata (PR #323)
    - [pre-commit 0.15.0](https://github.com/pre-commit/pre-commit/releases/tag/v0.15.0) was released for over a year (July 2017)
    - [pre-commit-hooks 0.9.0](https://github.com/pre-commit/pre-commit-hooks/releases/tag/v0.9.0) has also been around for over a year

**Comment by asottile** [comment]
This has been released 🎉 https://github.com/pre-commit/pre-commit-hooks/releases/tag/v2.0.0
